Fix random object being added to playmode
vrchat-community/ClientSim pull request #105
Opened 2023-10-12 13:02 UTC by Happyrobot33

Closes #96

Pretty simple fix, Assign the dummy gameobject created to a variable so we can destroy it once we are done with it

2023-10-12 22:52 UTC, Fairpl3x requested changes
There is no need to instantiate a dummy object and destroy it later. We can just make a local variable and directly set its parent to the _mainSceneCamera

2023-10-12 22:52 UTC, Fairpl3x commented on Packages/com.vrchat.ClientSim/Runtime/CameraStacking/ClientSimStackedVRCameraSystem.cs
> +            GameObject cameraObj = Instantiate(dummyObject, _mainSceneCamera.transform);
```suggestion
            GameObject cameraObj = new GameObject();
            cameraObj.transform.SetParent(_mainSceneCamera.transform);
```

2023-10-12 22:52 UTC, Fairpl3x commented on Packages/com.vrchat.ClientSim/Runtime/CameraStacking/ClientSimStackedVRCameraSystem.cs
> +            Destroy(dummyObject);
```suggestion

```

2023-10-13 09:33 UTC, Happyrobot33 commented
Fair enough, didn't want to be responsible for breaking anything in case the object being in scene mattered :)

2024-01-18 20:38 UTC, FairplexVR approved these changes
Good for me

2025-01-14 20:46 UTC, momo-the-monster commented
It looks like this was fixed in SDK 3.5.1, though the release notes did not mention it. Thanks for your contribution! That's why there's a conflict in the `ClientSimStackedVRCameraSystem.cs` file above.

2025-01-14 20:46 UTC, closed without merging